#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

EMERGENCY_STATE_FILE="${EMERGENCY_STATE_FILE:-}"
EMERGENCY_GATE_REQUIRED="${EMERGENCY_GATE_REQUIRED:-0}"
PYTHON_CMD=()
PYTHON_DESC=""

python_supports_project() {
  local candidate="$1"
  "$candidate" - <<'PY' >/dev/null 2>&1
import sys
raise SystemExit(0 if sys.version_info[:2] >= (3, 10) else 1)
PY
}

resolve_python_cmd() {
  if [[ -n "${DATAPULSE_RELEASE_PYTHON:-}" ]]; then
    if ! command -v "${DATAPULSE_RELEASE_PYTHON}" >/dev/null 2>&1; then
      fail "configured DATAPULSE_RELEASE_PYTHON not found: ${DATAPULSE_RELEASE_PYTHON}"
      return 1
    fi
    if ! python_supports_project "${DATAPULSE_RELEASE_PYTHON}"; then
      fail "configured DATAPULSE_RELEASE_PYTHON must be Python >= 3.10: ${DATAPULSE_RELEASE_PYTHON}"
      return 1
    fi
    PYTHON_CMD=("${DATAPULSE_RELEASE_PYTHON}")
    PYTHON_DESC="${DATAPULSE_RELEASE_PYTHON}"
    return 0
  fi

  for candidate in python3.12 python3.11 python3.10 python3; do
    if command -v "$candidate" >/dev/null 2>&1 && python_supports_project "$candidate"; then
      PYTHON_CMD=("$candidate")
      PYTHON_DESC="$candidate"
      return 0
    fi
  done

  if command -v uv >/dev/null 2>&1; then
    PYTHON_CMD=(uv run --python 3.10 python)
    PYTHON_DESC="uv run --python 3.10 python"
    return 0
  fi

  fail "no Python >= 3.10 runtime found; set DATAPULSE_RELEASE_PYTHON or install uv"
  return 1
}

python_run() {
  "${PYTHON_CMD[@]}" "$@"
}

show_help() {
  cat <<'EOF'
Usage:
  bash scripts/release_readiness.sh [--emergency-state /path/to/emergency_state.json] [--require-emergency-gate]

Flags:
  --emergency-state      Path to emergency_state.json generated by scripts/emergency_guard.sh
  --require-emergency-gate
                        Require emergency_state.json and fail if missing
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --emergency-state)
      EMERGENCY_STATE_FILE="$2"
      shift 2
      ;;
    --require-emergency-gate)
      EMERGENCY_GATE_REQUIRED=1
      shift
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "[WARN] unknown arg: $1 (ignored)"
      shift
      ;;
  esac
done

resolve_emergency_state_file() {
  local path="$1"
  if [[ -n "$path" ]]; then
    if [[ "$path" = /* ]]; then
      echo "$path"
    else
      echo "$ROOT_DIR/$path"
    fi
    return
  fi

  if [[ -n "${RUN_ID:-}" ]]; then
    echo "$ROOT_DIR/artifacts/openclaw_datapulse_${RUN_ID}/emergency_state.json"
  else
    echo ""
  fi
}

check_emergency_gate() {
  local state_file="$1"
  if [[ ! -f "$state_file" ]]; then
    if [[ "$EMERGENCY_GATE_REQUIRED" == "1" ]]; then
      fail "emergency state required but missing: $state_file"
    else
      pass "emergency state not found: $state_file"
    fi
    return
  fi

  local rc
  set +e
  python_run - <<'PY' "$state_file"
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
payload = json.loads(path.read_text(encoding="utf-8"))
stop = bool(payload.get("stop", False))
state = payload.get("state", {})
run_id = payload.get("run_id", "")
first_trigger = payload.get("first_trigger", "")
new_run = payload.get("should_new_run_id", False)
conclusion = payload.get("conclusion", "")
state_id = state.get("id", "")
state_name = state.get("name", "")

print(f"EMERGENCY_STATE={state_id} {state_name}")
print(f"EMERGENCY_RUN_ID={run_id}")
print(f"EMERGENCY_FIRST_TRIGGER={first_trigger or 'NONE'}")
print(f"EMERGENCY_NEW_RUN_REQUIRED={str(bool(new_run)).lower()}")
print(f"EMERGENCY_CONCLUSION={conclusion}")
if stop:
    print("EMERGENCY_STOP=true")
    raise SystemExit(2)
PY
  rc=$?
  set -e
  if [[ "$rc" -eq 2 ]]; then
    fail "emergency gate blocked by STOP in emergency state"
    return 0
  elif [[ "$rc" -ne 0 ]]; then
    fail "emergency gate parse failed with rc=$rc"
    return 0
  fi
  pass "emergency gate passed"
}

pass_count=0
fail_count=0

pass() {
  echo "[PASS] $1"
  pass_count=$((pass_count + 1))
}

fail() {
  echo "[FAIL] $1"
  fail_count=$((fail_count + 1))
}

check_required_file() {
  local path="$1"
  if [[ -e "$path" ]]; then
    pass "required file exists: $path"
  else
    fail "missing required file: $path"
  fi
}

check_cmd() {
  local name="$1"
  if command -v "$name" >/dev/null 2>&1; then
    pass "command available: $name"
  else
    fail "command unavailable: $name"
  fi
}

if [[ ! -d .git ]]; then
  fail "not a git repository root"
else
  pass "git repository detected"
fi

check_cmd jq || true
check_cmd gh || true

if resolve_python_cmd; then
  pass "release python runtime available: $PYTHON_DESC"
else
  echo "release readiness: pass=$pass_count fail=$fail_count"
  exit 1
fi

if grep -qxF ".claude/" .gitignore; then
  pass ".claude/ 已写入 .gitignore"
else
  fail ".claude/ 未写入 .gitignore"
fi

check_required_file "pyproject.toml"
check_required_file "README.md"
check_required_file "README_CN.md"
check_required_file "README_EN.md"
check_required_file "docs/contracts/openclaw_datapulse_tool_contract.json"
check_required_file "docs/openclaw_tavily_multi_execution_plan.json"
check_required_file "docs/release_checklist.md"
check_required_file "docs/search_gateway_config.md"
check_required_file "docs/release_rollback_guide.md"
check_required_file "scripts/release_publish.sh"
check_required_file "scripts/datapulse_local_smoke.sh"
check_required_file "scripts/datapulse_console.sh"
check_required_file "scripts/datapulse_console_smoke.sh"
check_required_file "scripts/datapulse_remote_openclaw_smoke.sh"

if python_run -m json.tool docs/contracts/openclaw_datapulse_tool_contract.json >/dev/null; then
  pass "openclaw contract JSON valid"
else
  fail "openclaw contract JSON invalid"
fi

if bash scripts/security_guardrails.sh; then
  pass "security guardrails passed"
else
  fail "security guardrails failed"
fi

if python_run -m compileall datapulse mcp_server.py >/dev/null 2>&1; then
  pass "python compile check passed"
else
  fail "python compile check failed"
fi

RUN_ID="${RUN_ID:-}"
EMERGENCY_STATE_FILE="$(resolve_emergency_state_file "$EMERGENCY_STATE_FILE")"
check_emergency_gate "$EMERGENCY_STATE_FILE"

echo "release readiness: pass=$pass_count fail=$fail_count"
if [[ "$fail_count" -ne 0 ]]; then
  exit 1
fi
echo "[OK] release readiness check passed"
